# This is the config file for the run_woof Rox AppDir.

LAYER_TYPE="overlay"
TERMINAL_COMMAND="xterm"
GTKDIALOG_COMMAND=""
CHECK_FOR_UPDATES="ask"
MERGE_UPDATES="ask"
DELETE_TMP="yes"
SELECTED_DEVX_PATH="/home/jonathan/woof-CE"
